### ISSUE TITLE
CdrReader to parse Odometry message

### ISSUE THREAD

**Issue by EnzoGhisoni** [foxglove/cdr#26]
**Description**

I'm using the class CdrReader in ReactJs application using @foxglove/ws-protocol to decode data provided by ros-foxglove-bridge on ROS2 installation. I'm able to decode simple messages such as string (std_msgs/msg/String) but I'm not able to decode it when it's more complicated message types (nav_msgs/msg/Odometry.msg https://docs.ros2.org/foxy/api/nav_msgs/msg/Odometry.html).

- Version:
"@foxglove/cdr": "^3.3.0",
"@foxglove/ws-protocol": "^0.7.2",

- Platform:
Ubuntu 22.04
Test in localhost
Data from ROS2 humble using ros-foxglove-bridge using commit [e37a3e1]

**Steps To Reproduce**

Here is the function that I use to start the websocket, subscribe to the odom topic and decode the received message:

```
import { FoxgloveClient } from "@foxglove/ws-protocol";
import { CdrReader } from "@foxglove/cdr";

async function subscriber_example(url: string) {
    const address = url.startsWith("ws://") || url.startsWith("wss://") ? url : `ws://${url}`;
    let fallbackMsgEncoding: string | undefined;
    
    console.log(`Client connecting to ${address}`);
    const client = new FoxgloveClient({
      ws: new WebSocket(address, [FoxgloveClient.SUPPORTED_SUBPROTOCOL]),
    });
    client.on("error", (error) => {
      console.log("Error", error);
      throw error;
    });
    client.on("serverInfo", (serverInfo) => {
      const supportedEncodings = serverInfo.supportedEncodings ?? [];
      fallbackMsgEncoding = supportedEncodings.find((encoding) =>
        SUPPORTED_MSG_ENCODINGS.includes(encoding),
      );
    });
    client.on("advertise", (services) => {
        // To get the topic odom
        const regexpSearch = new RegExp("/odom", 'i');
        const topic = services.find((s) =>regexpSearch.test(s.topic))
        
        console.log(topic);
        if (!topic) {
            return;
        }
        client.subscribe(topic.id);
        
    });
    client.on("message", (response) => {
        const reader = new CdrReader(response.data);
        console.log(reader.string())
    });
    }

export default subscriber_example

```

**Expected Behavior**

If the message is a string, the console.log(reader.string()) provides the published string. With an odom message, the console.log(reader.string()) provides the following output:
@�odombase_footprint{Q������ʑ���߿�575�?"B�5�����w5�Wi?��Y�0?�+����?�

Do you have an idea about how to solve this issue ?

**Comment by jtbandes** [comment]
Closing in favor of the discussion https://github.com/orgs/foxglove/discussions/990
